#!/usr/bin/env node

import { readFile, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { build } from 'esbuild'

const cwd = process.cwd()
const entryPoint = path.resolve(cwd, 'src/workers/trackParser.worker.ts')
const outputFile = path.resolve(cwd, 'public/workers/trackParser.worker.js')
const checkOnly = process.argv.includes('--check')

const result = await build({
  entryPoints: [entryPoint],
  absWorkingDir: cwd,
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['esnext'],
  charset: 'utf8',
  legalComments: 'none',
  logLevel: 'silent',
  minifySyntax: true,
  banner: {
    js: '// Generated by scripts/build-worker.mjs from src/workers/trackParser.worker.ts. Do not edit.',
  },
})

const generated = result.outputFiles[0].contents
if (checkOnly) {
  let current
  try {
    current = await readFile(outputFile)
  } catch {
    current = null
  }
  if (!current || !current.equals(generated)) {
    console.error('Generated worker is stale. Run: npm run build:worker')
    process.exit(1)
  }
  console.log('✓ Generated worker is current')
} else {
  await mkdir(path.dirname(outputFile), { recursive: true })
  await writeFile(outputFile, generated)
  console.log(`✓ Generated ${path.relative(cwd, outputFile)}`)
}
